### ISSUE TITLE
Heroku failed requests exceeded threshold of 5%

### ISSUE THREAD

**Issue by iteles** [club-soda/club-soda-guide#667]
Yesterday we received a number of emails from Heroku (roughly 1 per hour from 14:33 to 17:33) noting that the number of failed requests had exceeded our stated threshold of 5%.
There were none at all today.

![image](https://user-images.githubusercontent.com/4185328/99583610-afdcec80-29db-11eb-9b24-995ee807ee26.png)

@SimonLab Could you please take an hour to look into this and add the relevant logs here whilst they're still available?
It would be good to know what happened and if there is something that needs to be done 😊

**Comment by SimonLab** [comment]
The only error I've seen on the logs is the following:
```
** (FunctionClauseError) no function clause matching in String.split/3
 (elixir) lib/string.ex:366: String.split(nil, "/", [])
(cs_guide) lib/cs_guide_web/controllers/venue_controller.ex:80: 
CsGuideWeb.VenueController.json_index/2
```

This refers to the following function:

https://github.com/club-soda/club-soda-guide/blob/bc827d8c498c7cc92fe6846657c071e37ec23fe5/lib/cs_guide_web/controllers/venue_controller.ex#L76-L81

It looks like the `referer` is not defined in this case. linked to https://github.com/club-soda/club-soda-guide/issues/28#issuecomment-461077601

Otherwise I haven't spotted any other issues from the logs:
Heroku only keeps the latest 1500 logs https://devcenter.heroku.com/articles/logging#log-history-limits

**Comment by nelsonic** [comment]
@SimonLab seems like we need to add a test for when the `referer` is not set and create a fallback. 💭

**Comment by SimonLab** [comment]
I've also just spotted some weird requests to the server, e.g `/wp-login.php` and multiple requests with the following format:
`/accept_cookies//accept_cookies//accept_cookies//accept_cookies//accept_cookies//accept_cookies//accept_cookies//accept_cookies//accept_cookies//accept_cookies//brands/`

It looks like a  bot is sending some random requests. Heroku provides the fwd value for each request, see https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Forwarded-For . This value seems to be almost the same ip address

**Comment by iteles** [comment]
We had another (single) email this morning that the threshold had been crossed so it seems like this bot is the most likely cause.

Thanks for the diagnosis @SimonLab :+1:
